flink_iceberg:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: flink
      host: localhost
      port: 8083
      session_name: dbt_session
      database: default_catalog
      schema: default_database
      threads: 1
    aws:
      type: flink
      host: "{{ env_var('FLINK_GATEWAY_HOST') }}"
      port: 8083
      session_name: dbt_session
      database: default_catalog
      schema: default_database
      threads: 4
